final List<Map<String, dynamic>> initialExercises = [
  // ==========================================
  // --- CHEST (Anterior Torso) ---
  // ==========================================
  {"name": "Barbell Bench Press", "primary": "chest", "secondary": ["front_deltoids", "triceps", "side_deltoids"]},
  {"name": "Dumbbell Bench Press", "primary": "chest", "secondary": ["front_deltoids", "triceps", "side_deltoids"]},
  {"name": "Incline Barbell Press", "primary": "chest", "secondary": ["front_deltoids", "triceps"]}, 
  {"name": "Incline Dumbbell Press", "primary": "chest", "secondary": ["front_deltoids", "triceps"]},
  {"name": "Decline Barbell Press", "primary": "chest", "secondary": ["triceps", "front_deltoids"]},
  {"name": "Hammer Strength Wide Chest Press", "primary": "chest", "secondary": ["front_deltoids", "triceps"]},
  {"name": "Hammer Strength ISO-Lateral Incline Press", "primary": "chest", "secondary": ["front_deltoids", "triceps"]},
  {"name": "Hammer Strength ISO-Lateral Decline Press", "primary": "chest", "secondary": ["triceps", "front_deltoids"]},
  {"name": "Life Fitness Insignia Chest Press", "primary": "chest", "secondary": ["front_deltoids", "triceps"]},
  {"name": "Life Fitness Insignia Incline Press", "primary": "chest", "secondary": ["front_deltoids", "triceps"]},
  {"name": "Life Fitness Pro2 Chest Press", "primary": "chest", "secondary": ["front_deltoids", "triceps"]},
  {"name": "Life Fitness Pro2 Incline Press", "primary": "chest", "secondary": ["front_deltoids", "triceps"]},
  {"name": "Hoist Roc-it Chest Press", "primary": "chest", "secondary": ["front_deltoids", "triceps"]},
  {"name": "Hoist Roc-it Incline Press", "primary": "chest", "secondary": ["front_deltoids", "triceps"]},
  {"name": "Cable Fly (Middle)", "primary": "chest", "secondary": ["front_deltoids"]},
  {"name": "Cable Fly (High to Low)", "primary": "chest", "secondary": ["front_deltoids"]}, 
  {"name": "Cable Fly (Low to High)", "primary": "chest", "secondary": ["front_deltoids"]}, 
  {"name": "Dumbbell Flyes", "primary": "chest", "secondary": ["front_deltoids"]},
  {"name": "Pec Deck Machine", "primary": "chest", "secondary": ["front_deltoids"]},
  {"name": "Dips (Chest Focus)", "primary": "chest", "secondary": ["triceps", "front_deltoids"]},
  {"name": "Weighted Dips (Chest)", "primary": "chest", "secondary": ["triceps", "front_deltoids"]},
  {"name": "Push-ups", "primary": "chest", "secondary": ["triceps", "front_deltoids"]},

  // ==========================================
  // --- DELTOIDS ---
  // ==========================================
  {"name": "Overhead Barbell Press", "primary": "front_deltoids", "secondary": ["triceps", "side_deltoids", "traps", "upper_back"]},
  {"name": "Seated Dumbbell Press", "primary": "front_deltoids", "secondary": ["triceps", "side_deltoids", "traps"]},
  {"name": "Hammer Strength ISO-Lateral Shoulder Press", "primary": "front_deltoids", "secondary": ["triceps", "side_deltoids", "traps"]},
  {"name": "Life Fitness Insignia Shoulder Press", "primary": "front_deltoids", "secondary": ["triceps", "side_deltoids", "traps"]},
  {"name": "Hoist Roc-it Shoulder Press", "primary": "front_deltoids", "secondary": ["triceps", "side_deltoids", "traps"]},
  {"name": "Lateral Raise Machine (Life Fitness)", "primary": "side_deltoids", "secondary": ["front_deltoids", "traps"]},
  {"name": "Lateral Raise Machine (Hammer)", "primary": "side_deltoids", "secondary": ["front_deltoids", "traps"]},
  {"name": "Dumbbell Lateral Raise", "primary": "side_deltoids", "secondary": ["front_deltoids", "traps"]},
  {"name": "Cable Lateral Raise", "primary": "side_deltoids", "secondary": ["front_deltoids", "traps"]},
  {"name": "Dumbbell Front Raise", "primary": "front_deltoids", "secondary": ["side_deltoids"]},
  {"name": "Cable Front Raise", "primary": "front_deltoids", "secondary": ["side_deltoids"]},
  {"name": "Dumbbell Rear Delt Fly", "primary": "back_deltoids", "secondary": ["traps", "upper_back", "lats"]},
  {"name": "Cable Rear Delt Fly", "primary": "back_deltoids", "secondary": ["traps", "upper_back", "lats"]},
  {"name": "Reverse Pec Deck (Life Fitness)", "primary": "back_deltoids", "secondary": ["traps", "upper_back"]},
  {"name": "Hammer Strength Rear Delt", "primary": "back_deltoids", "secondary": ["traps", "upper_back"]},
  {"name": "Cable Face Pulls", "primary": "back_deltoids", "secondary": ["traps", "upper_back", "side_deltoids"]},
  {"name": "Upright Row (EZ Bar)", "primary": "side_deltoids", "secondary": ["traps", "front_deltoids", "biceps", "forearm"]},
  {"name": "Cable Upright Row", "primary": "side_deltoids", "secondary": ["traps", "front_deltoids", "biceps", "forearm"]},

  // ==========================================
  // --- BACK (Posterior Torso) ---
  // ==========================================
  {"name": "Hammer Strength ISO-Lateral Lat Pulldown", "primary": "lats", "secondary": ["biceps", "back_deltoids", "upper_back", "forearm"]},
  {"name": "Hammer Strength ISO-Lateral Front Pulldown", "primary": "lats", "secondary": ["biceps", "back_deltoids", "traps", "upper_back", "forearm"]},
  {"name": "Hammer Strength ISO-Lateral Dy-Row", "primary": "lats", "secondary": ["upper_back", "biceps", "traps", "back_deltoids", "forearm"]},
  {"name": "Hammer Strength ISO-Lateral High Row", "primary": "upper_back", "secondary": ["lats", "traps", "biceps", "back_deltoids", "forearm"]},
  {"name": "Hammer Strength ISO-Lateral Low Row", "primary": "lats", "secondary": ["upper_back", "traps", "biceps", "back_deltoids", "forearm"]},
  {"name": "Hammer Strength ISO-Lateral Row", "primary": "upper_back", "secondary": ["lats", "biceps", "traps", "back_deltoids", "forearm"]},
  {"name": "Life Fitness Insignia Lat Pulldown", "primary": "lats", "secondary": ["biceps", "back_deltoids", "upper_back", "forearm"]},
  {"name": "Life Fitness Insignia Row", "primary": "upper_back", "secondary": ["lats", "biceps", "traps", "back_deltoids", "forearm"]},
  {"name": "Life Fitness Pro2 Lat Pulldown", "primary": "lats", "secondary": ["biceps", "back_deltoids", "upper_back", "forearm"]},
  {"name": "Life Fitness Pro2 Seated Row", "primary": "upper_back", "secondary": ["lats", "biceps", "traps", "back_deltoids", "forearm"]},
  {"name": "Hoist Roc-it Lat Pulldown", "primary": "lats", "secondary": ["biceps", "back_deltoids", "upper_back", "forearm"]},
  {"name": "Hoist Roc-it Seated Row", "primary": "upper_back", "secondary": ["lats", "biceps", "traps", "back_deltoids", "forearm"]},
  {"name": "Cable Lat Pulldown (Wide Grip)", "primary": "lats", "secondary": ["biceps", "back_deltoids", "upper_back", "forearm"]},
  {"name": "Cable Lat Pulldown (Neutral Grip)", "primary": "lats", "secondary": ["biceps", "back_deltoids", "upper_back", "forearm"]},
  {"name": "Cable Lat Pulldown (Reverse Grip)", "primary": "lats", "secondary": ["biceps", "back_deltoids", "upper_back", "forearm"]},
  {"name": "Cable Seated Row", "primary": "upper_back", "secondary": ["lats", "biceps", "traps", "back_deltoids", "forearm"]},
  {"name": "Cable Straight Arm Pulldown", "primary": "lats", "secondary": ["triceps", "back_deltoids", "abs"]},
  {"name": "Barbell Deadlift", "primary": "lower_back", "secondary": ["glutes", "hamstrings", "traps", "upper_back", "quads", "forearm"]},
  {"name": "Barbell Row", "primary": "lats", "secondary": ["upper_back", "biceps", "traps", "lower_back", "forearm"]},
  {"name": "One Arm Dumbbell Row", "primary": "lats", "secondary": ["upper_back", "biceps", "traps", "back_deltoids", "forearm"]},
  {"name": "T-Bar Row", "primary": "upper_back", "secondary": ["lats", "biceps", "traps", "lower_back", "forearm"]},
  {"name": "Hyperextensions", "primary": "lower_back", "secondary": ["glutes", "hamstrings"]},
  {"name": "Life Fitness Back Extension", "primary": "lower_back", "secondary": ["glutes", "hamstrings"]},
  {"name": "Shrugs (Barbell)", "primary": "traps", "secondary": ["upper_back", "forearm"]},
  {"name": "Shrugs (Dumbbell)", "primary": "traps", "secondary": ["upper_back", "forearm"]},
  {"name": "Pull-ups", "primary": "lats", "secondary": ["biceps", "back_deltoids", "upper_back", "forearm"]},
  {"name": "Chin-ups", "primary": "biceps", "secondary": ["lats", "back_deltoids", "forearm"]},
  {"name": "Weighted Pull-ups", "primary": "lats", "secondary": ["biceps", "back_deltoids", "upper_back", "forearm"]},

  // ==========================================
  // --- BICEPS ---
  // ==========================================
  {"name": "Barbell Bicep Curl", "primary": "biceps", "secondary": ["forearm"]},
  {"name": "EZ Bar Bicep Curl (Close Grip)", "primary": "bicep_long_head", "secondary": ["bicep_short_head", "forearm"]},
  {"name": "EZ Bar Bicep Curl (Wide Grip)", "primary": "bicep_short_head", "secondary": ["bicep_long_head", "forearm"]},
  {"name": "Dumbbell Bicep Curl", "primary": "biceps", "secondary": ["forearm"]},
  {"name": "Incline Dumbbell Curl", "primary": "bicep_long_head", "secondary": ["bicep_short_head", "forearm"]},
  {"name": "Concentration Curl", "primary": "bicep_short_head", "secondary": ["forearm"]},
  {"name": "Dumbbell Hammer Curl", "primary": "forearm", "secondary": ["biceps"]}, 
  {"name": "Cable Hammer Curl (Rope)", "primary": "forearm", "secondary": ["biceps"]},
  {"name": "Preacher Curl Machine", "primary": "bicep_short_head", "secondary": ["bicep_long_head", "forearm"]},
  {"name": "Barbell Preacher Curl", "primary": "bicep_short_head", "secondary": ["bicep_long_head", "forearm"]},
  {"name": "Life Fitness Insignia Bicep Curl", "primary": "biceps", "secondary": ["forearm"]},
  {"name": "Life Fitness Pro2 Bicep Curl", "primary": "biceps", "secondary": ["forearm"]},
  {"name": "Hoist Roc-it Bicep Curl", "primary": "biceps", "secondary": ["forearm"]},
  {"name": "Cable Bicep Curl (Straight Bar)", "primary": "biceps", "secondary": ["forearm"]},

  // ==========================================
  // --- TRICEPS ---
  // ==========================================
  {"name": "Cable Tricep Pushdown (Straight Bar)", "primary": "triceps", "secondary": ["forearm"]},
  {"name": "Cable Tricep Pushdown (V-Bar)", "primary": "triceps", "secondary": ["forearm"]},
  {"name": "Cable Tricep Pushdown (Rope)", "primary": "triceps", "secondary": ["forearm"]},
  {"name": "Cable Overhead Tricep Extension (Rope)", "primary": "tricep_long_head", "secondary": ["triceps", "forearm"]},
  {"name": "Dumbbell Overhead Tricep Extension", "primary": "tricep_long_head", "secondary": ["triceps", "forearm"]},
  {"name": "Skull Crushers (EZ Bar)", "primary": "tricep_long_head", "secondary": ["triceps", "forearm"]},
  {"name": "Close Grip Barbell Bench Press", "primary": "triceps", "secondary": ["chest", "front_deltoids"]},
  {"name": "Tricep Dip Machine", "primary": "triceps", "secondary": ["chest", "front_deltoids"]},
  {"name": "Dips (Tricep Focus)", "primary": "triceps", "secondary": ["chest", "front_deltoids"]},
  {"name": "Weighted Dips (Tricep)", "primary": "triceps", "secondary": ["chest", "front_deltoids"]},
  {"name": "Life Fitness Insignia Tricep Extension", "primary": "triceps", "secondary": ["forearm"]},
  {"name": "Life Fitness Pro2 Tricep Extension", "primary": "triceps", "secondary": ["forearm"]},
  {"name": "Hammer Strength ISO-Lateral Dips", "primary": "triceps", "secondary": ["chest", "front_deltoids"]},

  // ==========================================
  // --- LEGS (Quads, Hamstrings, Glutes) ---
  // ==========================================
  {"name": "Barbell Back Squat", "primary": "quads", "secondary": ["glutes", "lower_back", "hamstrings", "adductors"]},
  {"name": "Barbell Front Squat", "primary": "quads", "secondary": ["upper_back", "glutes", "lower_back", "adductors"]},
  {"name": "Hack Squat Machine", "primary": "quads", "secondary": ["glutes", "hamstrings", "adductors"]},
  {"name": "Leg Press (Life Fitness Horizontal)", "primary": "quads", "secondary": ["glutes", "hamstrings", "adductors"]},
  {"name": "Leg Press (Hammer Strength 45-Degree)", "primary": "quads", "secondary": ["glutes", "hamstrings", "adductors"]},
  {"name": "Hoist Roc-it Leg Press", "primary": "quads", "secondary": ["glutes", "hamstrings", "adductors"]},
  {"name": "Life Fitness Insignia Leg Extension", "primary": "quads", "secondary": ["adductors"]},
  {"name": "Hammer Strength Leg Extension", "primary": "quads", "secondary": ["adductors"]},
  {"name": "Hoist Roc-it Leg Extension", "primary": "quads", "secondary": ["adductors"]},
  {"name": "Life Fitness Insignia Seated Leg Curl", "primary": "hamstrings", "secondary": ["glutes", "calves"]},
  {"name": "Hammer Strength Seated Leg Curl", "primary": "hamstrings", "secondary": ["glutes", "calves"]},
  {"name": "Life Fitness Pro2 Lying Leg Curl", "primary": "hamstrings", "secondary": ["glutes", "calves"]},
  {"name": "Romanian Deadlift (Barbell)", "primary": "hamstrings", "secondary": ["glutes", "lower_back"]},
  {"name": "Romanian Deadlift (Dumbbell)", "primary": "hamstrings", "secondary": ["glutes", "lower_back"]},
  {"name": "Bulgarian Split Squat (Dumbbell)", "primary": "quads", "secondary": ["glutes", "hamstrings", "adductors"]},
  {"name": "Walking Lunges (Dumbbell)", "primary": "quads", "secondary": ["glutes", "hamstrings", "adductors"]},
  {"name": "Standing Calf Raise Machine", "primary": "calves", "secondary": []},
  {"name": "Seated Calf Raise Machine", "primary": "calves", "secondary": []},
  {"name": "Hammer Strength Calf Raise", "primary": "calves", "secondary": []},
  {"name": "Life Fitness Insignia Calf Extension", "primary": "calves", "secondary": []},
  {"name": "Life Fitness Insignia Hip Abduction", "primary": "glutes", "secondary": []},
  {"name": "Life Fitness Insignia Hip Adduction", "primary": "adductors", "secondary": ["glutes"]},
  {"name": "Glute Kickback Machine", "primary": "glutes", "secondary": ["hamstrings"]},

  // ==========================================
  // --- ABS & CORE ---
  // ==========================================
  {"name": "Cable Crunch", "primary": "abs", "secondary": ["obliques"]},
  {"name": "Life Fitness Insignia Abdominal", "primary": "abs", "secondary": []},
  {"name": "Life Fitness Pro2 Abdominal", "primary": "abs", "secondary": []},
  {"name": "Hanging Leg Raise", "primary": "abs", "secondary": ["obliques"]},
  {"name": "Captains Chair Leg Raise", "primary": "abs", "secondary": ["obliques"]},
  {"name": "Russian Twist (Dumbbell)", "primary": "obliques", "secondary": ["abs"]},
  {"name": "Cable Woodchopper", "primary": "obliques", "secondary": ["abs"]},
  {"name": "Life Fitness Insignia Torso Rotation", "primary": "obliques", "secondary": ["abs"]},
  {"name": "Plank", "primary": "abs", "secondary": ["lower_back", "obliques"]}
];
